const API=(window.AFH_CONFIG||{}).API_URL||"";let D={settings:{},products:[]},P=null,C="",S="",Q=1;
const defaults={settings:{brand:"Arif Fashion House",hero:"Style • Quality • Reliable Service",heroSubtitle:"Trendy fashion with home delivery.",shipping:80,cod:true,advance:true,bkashNumber:"",nagadNumber:"",rocketNumber:"",facebook:"",youtube:"",warning:"আপনার অর্ডারটি নিশ্চিত করার আগে অনুগ্রহ করে পণ্য, সাইজ/কালার, ঠিকানা ও মোবাইল নম্বর ভালোভাবে যাচাই করুন।"},products:[{id:"demo",name:"Premium T-Shirt",category:"men",image:"",price:850,oldPrice:1000,colors:["Black","White"],sizes:["M","L","XL"],description:"Premium quality fashion product."}]};
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"),num=v=>Number(v||0).toLocaleString("en-US");
async function apiGet(a){if(!API)return null;try{return await (await fetch(API+"?action="+a)).json()}catch(e){return null}}
async function apiPost(o){if(!API)return null;try{return await (await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain"},body:JSON.stringify(o)})).json()}catch(e){return null}}
function norm(p){p=p||{};return {...p,id:String(p.id||p.productId||Date.now()),name:p.name||"Product",category:p.category||p.cat||"men",image:p.image||"",images:Array.isArray(p.images)?p.images:[],price:Number(p.price||0),oldPrice:Number(p.oldPrice||0),colors:Array.isArray(p.colors)?p.colors:[],sizes:Array.isArray(p.sizes)?p.sizes:[],description:p.description||""}}
async function boot(){try{D=JSON.parse(localStorage.getItem("afh_data")||"null")||defaults}catch(e){D=defaults}D.products=(D.products||[]).map(norm);let r=await apiGet("store");if(r?.ok)D=r.data;localStorage.setItem("afh_data",JSON.stringify(D));apply();render("all")}
function apply(){let s=D.settings||{};$("brandName").textContent=s.brand;$("footerBrand").textContent=s.brand;$("heroTitle").textContent=s.hero;$("heroSubtitle").textContent=s.heroSubtitle;$("warning").textContent=s.warning||defaults.settings.warning;if(s.facebook)$("facebookLink").href=s.facebook;else $("facebookLink").style.display="none";if(s.youtube)$("youtubeLink").href=s.youtube;else $("youtubeLink").style.display="none"}
function render(cat){let ps=D.products.filter(p=>cat=="all"||p.category==cat);$("products").innerHTML=ps.length?ps.map(p=>{let dis=p.oldPrice>p.price?Math.round((1-p.price/p.oldPrice)*100):0;return `<article class="card"><img src="${esc(p.image)}" onerror="this.style.display='none'"><div class="info"><h3>${esc(p.name)}</h3><span class="price">৳${num(p.price)}</span>${p.oldPrice>p.price?` <del class="old">৳${num(p.oldPrice)}</del> <span class="discount">-${dis}%</span>`:""}<button class="primary full" onclick="openProduct('${esc(p.id)}')">View & Order</button></div></article>`}).join(""):'<p>No products found.</p>'}
document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.cat)});
function openProduct(id){P=D.products.find(x=>x.id==id);C="";S="";Q=1;$("detailCategory").textContent=P.category.toUpperCase();$("detailName").textContent=P.name;$("detailPrice").textContent="৳"+num(P.price);$("detailOld").textContent=P.oldPrice>P.price?"৳"+num(P.oldPrice):"";$("detailDiscount").textContent=P.oldPrice>P.price?"-"+Math.round((1-P.price/P.oldPrice)*100)+"%":"";$("detailDescription").textContent=P.description||"";$("detailImage").src=P.image||"";$("qty").textContent=1;$("colors").innerHTML=(P.colors||[]).map(x=>`<button class="choice" onclick="selColor('${esc(x)}',this)">${esc(x)}</button>`).join("");$("sizes").innerHTML=(P.sizes||[]).map(x=>`<button class="choice" onclick="selSize('${esc(x)}',this)">${esc(x)}</button>`).join("");$("colorWrap").style.display=P.colors?.length?"block":"none";$("sizeWrap").style.display=P.sizes?.length?"block":"none";$("productModal").classList.remove("hidden");totalProduct()}
function selColor(x,e){C=x;document.querySelectorAll("#colors .choice").forEach(a=>a.classList.remove("selected"));e.classList.add("selected")}
function selSize(x,e){S=x;document.querySelectorAll("#sizes .choice").forEach(a=>a.classList.remove("selected"));e.classList.add("selected")}
function changeQty(n){Q=Math.max(1,Math.min(20,Q+n));$("qty").textContent=Q;totalProduct()}
function totalProduct(){$("productTotal").textContent="৳"+num((P?.price||0)*Q)}
function closeProduct(){$("productModal").classList.add("hidden")}
function goCheckout(){if(P.colors?.length&&!C)return alert("Please select a color.");if(P.sizes?.length&&!S)return alert("Please select a size.");closeProduct();$("checkoutImage").src=P.image||"";$("checkoutName").textContent=P.name;$("variantSummary").textContent=[C&&"Color: "+C,S&&"Size: "+S,"Qty: "+Q].filter(Boolean).join(" • ");$("shipping").textContent="৳"+num(D.settings.shipping);$("warning").textContent=D.settings.warning||defaults.settings.warning;$("paymentNumbers").innerHTML=[["bKash",D.settings.bkashNumber],["Nagad",D.settings.nagadNumber],["Rocket",D.settings.rocketNumber]].filter(x=>x[1]).map(x=>`<div><b>${x[0]}:</b> ${esc(x[1])}</div>`).join("");document.querySelector('input[value="COD"]').parentElement.style.display=D.settings.cod===false?"none":"block";document.querySelector('input[value="Advance"]').parentElement.style.display=D.settings.advance===false?"none":"block";$("checkoutModal").classList.remove("hidden");updateTotal()}
function updateTotal(){$("total").textContent="৳"+num(P.price*Q+Number(D.settings.shipping||0))}
function toggleConfirm(){$("confirmOrder").disabled=!$("confirmCheck").checked}
async function submitOrder(){let name=$("customerName").value.trim(),phone=$("customerPhone").value.trim(),address=$("customerAddress").value.trim();if(!name||!phone||!address)return alert("Please fill customer information.");let o={id:"AFH-"+Date.now(),date:new Date().toISOString(),name,phone,address,productId:P.id,productName:P.name,qty:Q,color:C,size:S,price:P.price,productTotal:P.price*Q,shipping:Number(D.settings.shipping||0),total:P.price*Q+Number(D.settings.shipping||0),payment:document.querySelector('input[name="payment"]:checked')?.value||"COD",transactionId:$("transactionId").value.trim(),status:"Pending",source:"Facebook / Website"};let a=JSON.parse(localStorage.getItem("afh_orders")||"[]");a.push(o);localStorage.setItem("afh_orders",JSON.stringify(a));let r=await apiPost({action:"createOrder",order:o});$("orderMsg").textContent=r?.ok?"✅ Order placed successfully. Order ID: "+o.id:"✅ Order saved. Order ID: "+o.id;$("confirmOrder").disabled=true}
function closeCheckout(){$("checkoutModal").classList.add("hidden")}
document.addEventListener("DOMContentLoaded",boot);